### ISSUE TITLE
module version mismatch

### ISSUE THREAD

**Issue by florian** [kapetan/osx-mouse#2]
I'm developing an Electron app which uses electron-drag. If I switch to the newest Electron version I get this error:

`
/Users/florian/…/node_modules/electron-drag/node_modules/osx-mouse/node_modules/…:83 Uncaught Error: Module version mismatch. Expected 47, got 46.
`

Do you have any idea what might cause this?

**Comment by kapetan** [comment]
I'll look into it. Which exact Electron version are you using?

**Comment by kapetan** [comment]
Did you compile `electron-drag` with the correct [Electron headers](https://github.com/electron/electron/blob/master/docs/tutorial/using-native-node-modules.md). There is a note about that in the readme.

**Comment by ahallicks** [comment]
I found the following to work in this instance. After you have run `npm install`:

```
cd node_modules/osx-mouse/

node-gyp configure
node-gyp rebuild --target={Electron verion} --arch=x64 --dist-url=https://atom.io/download/atom-shell
```

**Comment by florian** [comment]
Oh I'm sorry, I forgot to answer.
Rebuilding using `npm rebuild` fixed the issue for me :)

**Comment by diimdeep** [comment]
- node -v v6.3.1
- electron -v v1.3.2

in render.js
```
var drag = require('electron-drag');
```

`bindings.js:83 Uncaught Error: Module version mismatch. Expected 49, got 48.`

**Comment by diimdeep** [comment]
Had to `cd ..../osx-mouse` `node-gyp rebuild --target=1.3.2 --arch=x64 --dist-url=https://atom.io/download/atom-shell`

**Comment by maxmumford** [comment]
For anybody getting the following error:

```
Uncaught Error: The module '.../node_modules/osx-mouse/build/Release/addon.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 48. This version of Node.js requires
NODE_MODULE_VERSION 54. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or`npm install`).
```

The commands in the previous comment fix it
