### ISSUE TITLE
Remove OS from `package.json`

### ISSUE THREAD

**Issue by kevva** [kapetan/osx-mouse#3]
I'm trying to use this module, and `win-mouse` in a module but I can't install both of them because of this property. You could include the following in your `index.js` instead which wouldn't prevent users from installing it:

```js
if (process.platform !== 'darwin') {
    throw new Error('Only OS X systems are supported');
}
```

**Comment by kapetan** [comment]
It's not possible to compile `osx-mouse` on windows.

I'm using both `osx-mouse` and `win-mouse` in [electron-drag](https://github.com/kapetan/electron-drag) as optional dependencies.

**Comment by kevva** [comment]
Oh, right, that'd work.
